### PR TITLE
 Fixes #150. Removed cv2 dependency.

### LINKED ISSUE #150: make opencv dependency optional
https://github.com/pesser/edflow/blob/e4047d16d23c0c4a341ad95eda552f86676388ce/edflow/data/util.py#L9

this is the only place we are using opencv. its only use is for some optical flow functionality. since opencv is a bit of a heavy dependency, i would prefer to make it optional. both `eval/pipeline.py` and `util.py` import `data.util`, so we have to refactor the optical flow utilities into its own module. i suggest under `applications/`.

assigning the people of which i know they use optical flow - have fun :)

### PR DESCRIPTION
**Pull request by mritv**

### CODE REVIEW

**Comment by jhaux** [comment]
I like both the new keypoint plotting utility as well as getting rid of the cv2 dependency! Also the added tests are always welcome. Seems to me, we need to fix the naming of the test files, as recommended by pytest in the error message: `... use a unique basename for your test file modules`.

**Review by jhaux — CHANGES_REQUESTED** [review]
As per my comment above, I request the changing of the name of the test file `test_util.py`.

**Comment by mritv** [comment]
Changed the name to test_data_util.py

**Comment by pesser** [comment]
Sorry after merging #167 a conflict must be resolved. While at it, could you then also remove the opencv dependency from setup.py's install_requires?
Thanks for keeping edflow light!

**Comment by mritv** [comment]
Resolved the conflicts, can be merged now.

**Review by jhaux — CHANGES_REQUESTED** [review]
Please also delete opencv dependecy in setup.py,
Also please add changes to the changelog

**Comment by mritv** [comment]
Done :+1:

**Review by jhaux — APPROVED** [review]
Nice! Good example of how to add to the Change log!

**Pull request merged**
