### PR TITLE
Edsetup

### PR DESCRIPTION
**Pull request by mritv**
Edsetup for creating a new edflow project directory and necessary files. Edflow compatible.

### CODE REVIEW

**Review by pesser — APPROVED** [review]
looks great, just the test is failing. should be fixed once you add `edsetup` to `setup.py`

**Comment by mritv** [comment]
edflow needs to be reinstalled for the files to be therebusing `pip install -e .`. Is that possible?

**Comment by pesser** [comment]
maybe its better to have the template files installed into site-packages and have edsetup copy them from there? then we don't need to rely on editable installs.
you should be able to specify them in `package_data` in `setup.py` https://setuptools.readthedocs.io/en/latest/setuptools.html#including-data-files

**Comment by mritv** [comment]
:tada: :tada:

**Pull request merged**
